### ISSUE TITLE
Strong version limitations needed?

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/poetry-feedstock#39]
Are the strong version limitations on almost all dependencies needed? This gives version clashses for packages that want to use poetry:

https://github.com/conda-forge/pkgconfig-feedstock/pull/27

**Comment by ocefpaf** [comment]
Those specified upstream. Not sure if we can relax them and still get a working poetry package.

**Comment by tdegeus** [comment]
That is unfortunate, I was hoping they were introduced by an overprice feedstock maintainer. Do you have any suggestions how to proceed with pkgconfig then?

**Comment by ocefpaf** [comment]
I can take a look at what is blocking and trying to rebuild versions for it. We can also try to relax poetry's deps b/c upstream can be too conservative. But in that case we would need to run the full test suite in the feedstock. Do you want to try a PR to the latter? (Probably easier than the former!)

**Comment by tdegeus** [comment]
@ocefpaf I can try to prepare a PR, but the priority to do so is not very high as I am not a poetry user at all. I just crossed it for pkgconfig. So it might be a while before I get around to do so

**Comment by ocefpaf** [comment]
No worries. Also, I think that the issue with pkgconfig was resolved, right?

**Comment by tdegeus** [comment]
Indeed. That makes the priority even lower ;). Note that I think that it was crucial to switch away from this feedstock to https://github.com/conda-forge/poetry-core-feedstock

**Comment by xylar** [comment]
@tdegeus, has this issue been resolved for you?  If so, can we close it?  Even if there are similar issues for others in the future, it might be more useful to open a new issue.

**Comment by tdegeus** [comment]
@xylar In pkgconfig we worked around. I cannot say anything else since I'm not a poetry user. So from my side I'm fine with closing. Though from afar I would still say that, if possible, it would be nice to get rid of some of the narrow version requirements.

**Comment by xylar** [comment]
@tdegeus, I understand your concern but it's equally important that we stick very strictly to the version constraints that the original package prescribes.  So if constraints can be loosened, that would be a decision that would need to be made at https://github.com/python-poetry/poetry and not here.  The same goes for any conda-forge feedstock.

I will close this for now.
