### ISSUE TITLE
Update the importlib-metadata to >=1.6.0 After next poetry release >1.0.8

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/poetry-feedstock#61]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/python-poetry/poetry/commit/c5ac467f708f5be06b20078b0ed5b5fc427c6ff5

Poetry has updated the importlib-metadata to >=1.6.0

importlib-metadata = { version = ">=1.6.0", python = "<3.8" }

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by maresb** [comment]
@rxm7706, if you'd like to be free of the restrictive importlib-metadata pin, you can run [this command](https://github.com/conda-forge/poetry-feedstock/issues/57#issuecomment-1022805023) with `1.2.0a2` replaced by `1.2.0b1`.

**Comment by rxm7706** [comment]
@maresb - that worked, thank you. 

`mamba install -c conda-forge/label/poetry_dev -c conda-forge/label/cleo_dev -c conda-forge "poetry==1.2.0b1"`

**Comment by maresb** [comment]
Great! I think we can close the issues since in any case we update the dependencies on each release. (We won't forget.)
