### ISSUE TITLE
How to add poetry-plugin-export

### ISSUE THREAD

**Issue by maresb** [conda-forge/poetry-feedstock#65]
### Comment:

I would like to build the latest beta version v1.2.0b2. However it [now depends on](https://github.com/python-poetry/poetry/blob/ccbeffc1f1a5809e999cc18c584ed2cee2a8f580/pyproject.toml#L48) ^1.0.4 of a package called `poetry-plugin-export`. In a partially circular dependency, that relies on poetry [^1.2.0b1](https://github.com/python-poetry/poetry-plugin-export/blob/dca6dbb87c8450b6e7e46a572ef8aa8af0692e50/pyproject.toml#L19).

To complicate matters further, poetry-plugin-export [doesn't have a license file](https://github.com/python-poetry/poetry-plugin-export/issues/80).

I think I should make a new feedstock for `poetry-plugin-export`, but that must target the [dev channel sources](https://github.com/conda-forge/poetry-feedstock/blob/dev/recipe/conda_build_config.yaml). I'm not sure if that's allowed in [staged-recipes](https://github.com/conda-forge/staged-recipes).

As you can see, the situation is unfortunately rather complicated. Any suggestions?

**Comment by ocefpaf** [comment]
> As you can see, the situation is unfortunately rather complicated. Any suggestions?

Your plan sounds good. Note that `poetry-plugin-export` depends on `poetry-core` and not `poetry`. That should help you with the circular dependency.

**Comment by xylar** [comment]
@maresb, it is fine to make a new recipe for a non-release very of a package. Just make sure it goes to a dev label (poetry_dev would make sense in this case). I'll post a link to an example recipe soon.

**Comment by xylar** [comment]
Also, feel free to make me a maintainer if you want.

**Comment by maresb** [comment]
Thanks @xylar, let's give it a try. However, I think there is no point in starting before they create a LICENSE file.

**Comment by xylar** [comment]
Here's the example I had in mind https://github.com/conda-forge/staged-recipes/pull/18565

Just make sure you have the conda_build_config.yaml

**Comment by xylar** [comment]
@maresb, yes, you're right about that. If you can find out what license they want to include in some official way, you can include it in the recipe for now. But no license is a show stopper.

**Comment by maresb** [comment]
Ah, that's great! For some reason I couldn't build locally (neither `conda build` nor `conda mambabuild`) because it didn't seem to be parsing my `conda_build_config.yaml`.

**Comment by maresb** [comment]
They declared MIT, but I feel uneasy producing a LICENSE file for someone else.

**Comment by xylar** [comment]
You're right. If they add it to their repo, we could copy it into the recipe so we don't have to wait for a release. But to add a license file for somewhere else would be iffy.

**Comment by maresb** [comment]
This exists now at https://github.com/conda-forge/poetry-plugin-export-feedstock :tada:
