### ISSUE TITLE
Unable to pull poetry package on conda-forge

### ISSUE THREAD

**Issue by dwsmith1983** [conda-forge/poetry-feedstock#86]
### Comment:

I have been trying to pull the poetry package from `conda-forge` for a OSX. However, it will never resolve.
```bash
base ❯ conda install -c conda-forge poetry
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / failed

CondaError: KeyboardInterrupt


~ 1h 2m 34s
```
It ran for over 1 hour. This is a fresh install of Anaconda with only `conda upgrade conda anaconda --a` being run. I have tried numerous times over the past two days. I have also added `conda-forge` for the channels and set priority to strict and still no luck.

**Comment by ocefpaf** [comment]
If you are installing into an existing environment, the solve times can be quite unwieldy. Please try a fresh env with:


 ```
conda create --name TEST poetry  --channel conda-forge 
```

Also, can you post your condarc? BTW, for faster solve times you can try to enable libmamba, see https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community for more info.

**Comment by dwsmith1983** [comment]
@ocefpaf libmamba worked. However, their (Anaconda's) current setup pretty much renders the package install useless. Thanks for the help.
